--Excercise 3
--a)create table named lms_book_details
create table lms_book_details(
BOOK_CODE VARCHAR2(100),
BOOK_TITLE VARCHAR2(100),
CATEGORY VARCHAR2(100),
AUTHOR VARCHAR2(100),
PUBLICATION VARCHAR2(100),
PUBLISH_DATE DATE,
BOOK_EDITION NUMBER,
PRICE NUMBER,
RACK_NUM VARCHAR2(100),
DATE_ARRIVAL DATE,
SUPPLIER_ID VARCHAR2(100));

--B)DROP TABLE
DROP TABLE lms_book_details;

--C)TABLE CREATED AGAIN FIRING OPTION A

--D)ALTER THE TABLE
--I)ADD TWO MORE COLUMNS ISBN VARCHAR2 CURRENCY VARCHAR2
ALTER TABLE LMS_BOOK_DETAILS
ADD ISBN VARCHAR2(100)
ADD CURRENCY VARCHAR2(100);

--II)RENAME THE CURRENCY COLUMN NAME TO BOOK_CURRENCY
ALTER TABLE LMS_BOOK_DETAILS
RENAME COLUMN CURRENCY TO BOOK_CURRENCY;

SELECT * FROM LMS_BOOK_DETAILS;
--III)DROP THE ISBN COLUMN
ALTER TABLE LMS_BOOK_DETAILS
DROP COLUMN ISBN;

--IV)RENAME THE TABLE TO LMS_BOOK_DETAILS_P.
RENAME LMS_BOOK_DETAILS TO LMS_BOOK_DETAILS_P;

--E)INSERT FOLLOWING DATA
INSERT INTO lms_book_details_p(book_code,BOOK_TITLE,CATEGORY,AUTHOR,PUBLICATION,PUBLISH_DATE,BOOK_EDITION,PRICE,RACK_NUM,DATE_ARRIVAL,SUPPLIER_ID)
VALUES('BL000001',
'Java How To Do Program',
'JAVA',
'Paul J. Deitel', 
'Prentice Hall',
TO_DATE('10-12-1999','dd-mm-yyyy'),
6,
600,
'A1',
TO_DATE('10-05-2011','DD-MM-YYYY')
,'S01');

INSERT INTO lms_book_details_p(book_code,BOOK_TITLE,CATEGORY,AUTHOR,PUBLICATION,PUBLISH_DATE,BOOK_EDITION,PRICE,RACK_NUM,DATE_ARRIVAL,SUPPLIER_ID)
VALUES('BL000002',
'Java: The Complete Reference',
'JAVA',
'Herbert Schildt', 
'Tata Mcgraw Hill',
TO_DATE('10-10-2011','dd-mm-yyyy'),
5,
750,
'A1',
TO_DATE('10-05-2011','DD-MM-YYYY')
,'S03');
--[2 ROWS]
DELETE FROM lms_book_details_p;
--[ 0 ROWS]
 --G)INSERT THE DATA BACK AGAIN IN POINT (E)
 SELECT * FROM LMS_BOOK_DETAILS_P;
--[2 ROWS]
--H)UPDATE FOR ALL ROWS CATEGORY COLUMN TO 'JUNK'
UPDATE LMS_BOOK_DETAILS_P
SET  CATEGORY = 'JUNK';
 SELECT * FROM LMS_BOOK_DETAILS_P;
 --[2 ROWS]
 INSERT INTO lms_book_details_p(book_code,BOOK_TITLE,CATEGORY,AUTHOR,PUBLICATION,PUBLISH_DATE,BOOK_EDITION,PRICE,RACK_NUM,DATE_ARRIVAL,SUPPLIER_ID)
VALUES('BL000003',
'Java How to do program',
'JAVA',
'Paul J. Deitel', 
'Prentice Hall',
TO_DATE('10-05-1999','dd-mm-yyyy'),
6,
600,
'A1',
TO_DATE('10-05-2012','DD-MM-YYYY')
,'S01');
 --[3 rows]
 rollback;
 
 --[0 rows]
SELECT * FROM LMS_BOOK_DETAILS_P;
--[0 rows]
INSERT INTO lms_book_details_p(book_code,BOOK_TITLE,CATEGORY,AUTHOR,PUBLICATION,PUBLISH_DATE,BOOK_EDITION,PRICE,RACK_NUM,DATE_ARRIVAL,SUPPLIER_ID)
VALUES('BL000003',
'Java How to do program',
'JAVA',
'Paul J. Deitel', 
'Prentice Hall',
TO_DATE('10-05-1999','dd-mm-yyyy'),
6,
600,
'A1',
TO_DATE('10-05-2012','DD-MM-YYYY')
,'S01');
--[1 row]

SELECT * FROM LMS_BOOK_DETAILS_P;
--[1 row}
commit;
--[1 row]
 savepoint s1;
 INSERT INTO lms_book_details_p(book_code,BOOK_TITLE,CATEGORY,AUTHOR,PUBLICATION,PUBLISH_DATE,BOOK_EDITION,PRICE,RACK_NUM,DATE_ARRIVAL,SUPPLIER_ID)
VALUES('BL000004',
'Java: The Complete Reference',
'JAVA',
'Herbert Schildt', 
'Tata McGraw Hill',
TO_DATE('10-10-2011','dd-mm-yyyy'),
5,
750,
'A1',
TO_DATE('11-05-2012','DD-MM-YYYY')
,'S01');
--[2 row]
savepoint s2;
 INSERT INTO lms_book_details_p(book_code,BOOK_TITLE,CATEGORY,AUTHOR,PUBLICATION,PUBLISH_DATE,BOOK_EDITION,PRICE,RACK_NUM,DATE_ARRIVAL,SUPPLIER_ID)
VALUES('BL000005',
'Java How to do program',
'JAVA',
'Paul J. Deitel', 
'Prentice Hall',
TO_DATE('10-05-1999','dd-mm-yyyy'),
6,
600,
'A1',
TO_DATE('10-05-2012','DD-MM-YYYY')
,'S01');
--[3 rows]
rollback to savepoint s2;
--[2 rows]
select * from lms_book_details_p;
--[2 rows]