--Excercise 4
--a)create table named lms_book_issue
create table lms_book_issue(
BOOK_ISSUE_NO NUMBER,
MEMBER_ID VARCHAR2(100),
BOOK_CODE VARCHAR2(100),
DATE_ISSUE DATE,
DATE_RETURN DATE,
DATE_RETURNED DATE,
FINE_RANGE VARCHAR2(100));

--B)DROP TABLE
DROP TABLE lms_book_issue;

--C)TABLE CREATED AGAIN FIRING OPTION A
create table lms_book_issue(
BOOK_ISSUE_NO NUMBER,
MEMBER_ID VARCHAR2(100),
BOOK_CODE VARCHAR2(100),
DATE_ISSUE DATE,
DATE_RETURN DATE,
DATE_RETURNED DATE,
FINE_RANGE VARCHAR2(100));
--D)ALTER THE TABLE
--I)ADD TWO MORE COLUMNS VENDOR_CODE VARCHAR2 PLACE VARCHAR2
ALTER TABLE lms_book_issue
ADD VENDOR_CODE VARCHAR2(100)
ADD PLACE VARCHAR2(100);

--II)RENAME THE PLACE COLUMN NAME TO VENDOR_PLACE
ALTER TABLE lms_book_issue
RENAME COLUMN PLACE TO VENDOR_PLACE;

SELECT * FROM lms_book_issue_P;
--III)DROP THE VENDOR_CODE COLUMN
ALTER TABLE lms_book_issue
DROP COLUMN VENDOR_CODE ;

--IV)RENAME THE TABLE TO lms_book_issue_p.
RENAME lms_book_issue TO lms_book_issue_p;

--E)INSERT FOLLOWING DATA
INSERT INTO lms_book_issue_p(BOOK_ISSUE_NO,MEMBER_ID,BOOK_CODE,DATE_ISSUE,DATE_RETURN,DATE_RETURNED,FINE_RANGE)
VALUES(6,'LM003','BL000007',TO_DATE('22-04-2012','DD-MM-YYYY'),TO_DATE('07-05-2012','DD-MM-YYYY'),TO_DATE('25-05-2012','DD-MM-YYYY'),'R4');

INSERT INTO lms_book_issue_p(BOOK_ISSUE_NO,MEMBER_ID,BOOK_CODE,DATE_ISSUE,DATE_RETURN,DATE_RETURNED,FINE_RANGE)
VALUES(12,'LM003','BL000001',TO_DATE('22-04-2013','DD-MM-YYYY'),TO_DATE('07-05-2013','DD-MM-YYYY'),TO_DATE('25-05-2013','DD-MM-YYYY'),'R4');
--[2 ROWS]
DELETE FROM lms_book_issue_p;
--[ 0 ROWS]
 --G)INSERT THE DATA BACK AGAIN IN POINT (E)
 SELECT * FROM lms_book_issue_p;
--[2 ROWS]
--H)UPDATE FOR ALL ROWS BOOK_CODE COLUMN TO 'B0000001111'
UPDATE lms_book_issue_p
SET  BOOK_CODE = 'B0000001111';
 SELECT * FROM lms_book_issue_p;
 --[2 ROWS]
 INSERT INTO lms_book_issue_p(BOOK_ISSUE_NO,MEMBER_ID,BOOK_CODE,DATE_ISSUE,DATE_RETURN,DATE_RETURNED,FINE_RANGE)
VALUES(18,'LM003','BL000007',TO_DATE('07-05-2012','DD-MM-YYYY'),TO_DATE('22-05-2012','DD-MM-YYYY'),TO_DATE('11-06-2012','DD-MM-YYYY'),'R4');
 --[3 rows]
 rollback;
 
 --[0 rows]
SELECT * FROM lms_book_issue_p;
--[0 rows]
INSERT INTO lms_book_issue_p(BOOK_ISSUE_NO,MEMBER_ID,BOOK_CODE,DATE_ISSUE,DATE_RETURN,DATE_RETURNED,FINE_RANGE)
VALUES(18,'LM003','BL000007',TO_DATE('07-05-2012','DD-MM-YYYY'),TO_DATE('22-05-2012','DD-MM-YYYY'),TO_DATE('11-06-2012','DD-MM-YYYY'),'R4');
--[1 row]

SELECT * FROM lms_book_issue_p;
--[1 row}
commit;
--[1 row]
 savepoint s1;
 INSERT INTO lms_book_issue_p(BOOK_ISSUE_NO,MEMBER_ID,BOOK_CODE,DATE_ISSUE,DATE_RETURN,DATE_RETURNED,FINE_RANGE)
VALUES(24,'LM003','BL000007',TO_DATE('07-05-2013','DD-MM-YYYY'),TO_DATE('22-05-2013','DD-MM-YYYY'),TO_DATE('11-06-2013','DD-MM-YYYY'),'R4');
--[2 row]
savepoint s2;
INSERT INTO lms_book_issue_p(BOOK_ISSUE_NO,MEMBER_ID,BOOK_CODE,DATE_ISSUE,DATE_RETURN,DATE_RETURNED,FINE_RANGE)
VALUES(18,'LM003','BL000007',TO_DATE('07-05-2012','DD-MM-YYYY'),TO_DATE('22-05-2012','DD-MM-YYYY'),TO_DATE('11-06-2012','DD-MM-YYYY'),'R4');
--[3 rows]
rollback to savepoint s2;
--[2 rows]
select * from lms_book_details_p;
--[2 rows]